### ISSUE TITLE
HotTowel.Angular not working after installing 

### ISSUE THREAD

**Issue by rahulsahay19** [johnpapa/HotTowel-Angular#21]
Hi John,

I was testing HotTowel.Angular package. I have downloaded this package from Nuget. It Installed all the required components. But when i opened the index.html page in chrome(any browser), it kept showing me {{vm.busymessage}}. 

When i opened the developer tool i found many 404 and dependency error. However, in nuget tool, it flagged the app installed successfully.
Below i have attached the screen shots.

![2nd](https://cloud.githubusercontent.com/assets/3886381/5993231/28643d90-aa6f-11e4-918f-d56afc01cd3b.png)

![1st](https://cloud.githubusercontent.com/assets/3886381/5993218/b62c7526-aa6e-11e4-99df-d0de0c4463ab.png)

![3rd](https://cloud.githubusercontent.com/assets/3886381/5993232/324bd43a-aa6f-11e4-9caf-2d90d043eab4.png)

Thanks,
Rahul

**Comment by hmzahzeade** [comment]
<script src="Scripts/jquery-2.1.3.min.js"></script>

**Comment by JoeRobles** [comment]
You have to install bower dependencies, by running "bower install" and npm dependencies by running "npm install" then you will be able to run the app by running "gulp serve-dev".

**Comment by rahulsahay19** [comment]
Sorry to bother you. I thought, i have closed this ticket. I have fixed the
issue same day, when i raised it. anyways, thanks for getting back to me

On Fri, Sep 18, 2015 at 8:12 AM, Joe Robles notifications@github.com
wrote:

> You have to install bower dependencies, by running "bower install" and npm
> dependencies by running "npm install" then you will be able to run the app
> by running "gulp serve-dev".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/johnpapa/HotTowel-Angular/issues/21#issuecomment-141321201
> .

## 

[image: --]

rahul sahay
[image: http://]about.me/rahulsahay19
http://about.me/rahulsahay19?promo=email_sig

**Comment by rahulsahay19** [comment]
closing!
