### ISSUE TITLE
Question : Do you plan support for TypeScript ?

### ISSUE THREAD

**Issue by StefH** [johnpapa/HotTowel-Angular#5]
Hi John,

Thanks for latest change in the template.

I was wondering, do you plan to create a "HotTowel-Angular-TypeScript" version? I would really love to see a TypeScript + requirejs version from this application because I tried building a demo application using all these frameworks, but I'm stuck at requirejs.

Best regards,
Stef

**Comment by johnpapa** [comment]
@StefH TypeScript is a good idea. I may do that, but its not on my short term radar.  I'll leave this here to remind me,

**Comment by StefH** [comment]
Hi @johnpapa, I've created an HotTowel-Angular project using your template and did replace the javascripts by typescripts. (I'm just starting to use typescript, so maybe there are some small mistakes, so please review.)

Repository can be found at:
https://github.com/StefH/HotTowelAngularTS

**Comment by johnnyreilly** [comment]
Hi @johnpapa (and @StefH too!),

It looks like I'm retreading old ground here but I too have ported `HotTowel-Angular` to TypeScript here:

https://github.com/johnnyreilly/HotTowel-Angular-TypeScript

Having looked at @StefH's repo I can see that I've ploughed a slightly different furrow.  I've deliberately restricted my port to only make use of types.  My port is as close to John's original code as possible.  There's certainly scope to make use of TypeScripts other features in HotTowel-Angular as well (eg controllers, given their constructor function nature would probably be good candidates to port to TypeScript / ES6 classes).  

But the purpose of my port is deliberately to demonstrate the low barrier to entry when moving to using TypeScript.

If you'd like to make use of this in any way @johnpapa then feel free - the code is (quite literally) yours.  All I've really done is add type annotations.  Thanks for your ongoing Pluralsight work by the way - you are my commuting companion!

Best,
John

**Comment by johnpapa** [comment]
i think that port is a good option for typescript devs
