### ISSUE TITLE
Using without ASP.NET

### ISSUE THREAD

**Issue by cayblood** [johnpapa/HotTowel-Angular#9]
I heard about HotTowel on Yet Another Podcast and am interested in taking a look at your basic seed app, but I'm not an ASP.NET user and not really interested in becoming one. Can I just extract HotTowel-Angular/NuGet/HotTowel-NG to use as my starting point or does the IDE do some additional code generation that I should be aware of?

**Comment by johnpapa** [comment]
Yes, you can, but the easiest way to just try it out without any environment restrictions is to check out  https://github.com/johnpapa/ng-demos/tree/master/hottowel
